// colors.ts
export const Colors = {
  light: {
    background: "#FFFFFF",
    backgroundGray: "#F2F2F7",
    black: "#000000",
    backgroundPrimary: "#FEFAEC",
    text: "#1A1A1A",
    textWhite: "#FFFFFF",
    textGray: "#64748B",
    textLightGray: "#A0A0A0",
    primary: "#EF702A",
    secondary: "#FFCB11",
    accent: "#FFCB11",
    yellow: "#F8BD3C",
    accentRed: "#FF383C",
    accentBlue: "#1B1A57",
    brown: "#312920",
    purple: "#5A3D8B",
    blue: "#3B82F6",
    green: "#4BB543",
    success: "#4BB543",
    successLight: "#E8F5E9",
    warning: "#FFAA00",
    warningLight: "#FFF3E0",
    error: "#FF3B30",
    errorLight: "#FFEBEE",
    inputBg: "#FFFFFF",
    backgroundSecondary: "#F8F9FA",
    primaryLight: "#FFF4ED",
    selectBg: "#FAFAFA",
    iconBlack: "#1C1C28",
    iconGray: "#64748B",
    iconLightGray: "#EFEFEF",
    iconWhite: "#FFFFFF",
    border: "#E2E8F0",
    placeholder: "#999999",
  },

  dark: {
    background: "#0A0A0A",
    backgroundGray: "#181818",
    backgroundPrimary: "#212121",
    black: "#333333",
    text: "#FFFFFF",
    textGray: "#FEFEFE",
    textLightGray: "#D4D4D8",
    textWhite: "#ffffff",
    primary: "#FF823A", // Enhanced orange for dark mode
    secondary: "#FFD84A", // Enhanced yellow for dark mode
    accent: "#FFD84A", // Added accent color for dark mode
    yellow: "#F8BD3C",
    accentRed: "#FF6B6B",
    accentBlue: "#FEFEFE",
    brown: "#5C4B43",
    blue: "#60A5FA",
    purple: "#9D7CD8",
    green: "#22946e",
    success: "#22946e",
    successLight: "#1B3A2F",
    warning: "#FFB547",
    warningLight: "#3D3020",
    error: "#FF6B6B",
    errorLight: "#3D2020",
    inputBg: "#1A1A1A",
    backgroundSecondary: "#1C1C1C",
    primaryLight: "#2D1F15",
    selectBg: "#222222",
    iconBlack: "#FCFCF8",
    iconWhite: "#FCFCF8",
    iconGray: "#FEFEFE",
    iconLightGray: "#A1A1A1",
    border: "#333333",
    placeholder: "#CCCCCC",
  },
};

export type ThemeMode = keyof typeof Colors;
